# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'ru-ru'
words_per_minute: 200
incremental: true

baseurl: /

# Website info
title: '[EXMPL]Example'
description: Выбирайте путь сложней - там меньше конкурентов...
cover: assets/images/site/blog-cover.jpg
logo: assets/images/site/clan-logo.png
logo_dark: assets/images/site/favicon.png
favicon: assets/images/site/favicon.png
CNAME: #add cname for website to be created

# Social info
navigation: true # show the navbar links
subscribers: true # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: tryghost # replace by your username
facebook: ghost # replace by your username

#social networks
vk: false
ok: false
dzen: false
youtube: false
discord: false
teamspeak: false
telegram: false
trovo: false
twitch: false
tiktok: false

#sponsors
sponsors: false

# emoji
smileytheme: MSN

disqus: False
disqus_shortname: jekyllt # replace with your disqus username

google_analytics: UA-69281367-1 # replace with your GA tracking identifier

permalink: /:title
# permalink: /member/:member
# permalink: /category/:category

plugins_dir: [_plugins]
plugins: [jekyll-paginate]

safe: false
lsi: false
username: jekyllt
repo: jasper2
branch: master
relative_source: ../jasper2/
destination: ../jasper2-pages/
production_url:  https://jekyllt.github.io/jasper2/
source_url:  https://github.com/jekyllt/jasper2/

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "*.Rmd", ".git*", ".sass-cache", ".jekyll-cache"]